### ISSUE TITLE
setSameOriginTransitionElements

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#53] opened 2021-08-23 14:15 UTC
```js
document.documentTransition.setSameOriginTransitionElements({
  "foo.com/a.html": [{ element: document.html }],
});
```

I'm not keen on this API, but I'm not sure I understand the thinking behind it, so there might be good reasons.

As it stands, it seems to encourage a lot of up-front work, providing all the elements and data for every possible transition to every possible URL, when a maximum of one will be used.

This pattern seems better:

```js
appHistory.addEventListener("navigate", (e) => {
  if (isSameOrigin(e.destination)) {
    document.documentTransition.setSameOriginTransitionElements({
      [e.destination.url]: [{ element: document.html }],
    });
  }
});
```

However, it's now complicated by the origin check, and the `[e.destination.url]` bit. Also, this won't work if the navigation features a redirect.

How about something like:

```js
appHistory.addEventListener("navigate", (event) => {
  event.addSameOriginDocumentTransitionHandler((destinationURL) => {
    return {
      elements: [{ element: document.html }],
    };
  });
});
```

`addSameOriginDocumentTransitionHandler` is a horrible name, so there's probably a better option there. However, it means that `destinationURL` can be the final URL (after redirects), and the developer can write whatever code they want to change the type of transition based on the URL.

**Comment by khushalsagar** [comment] 2021-09-08 16:19
My thinking behind going with a setSameOriginTransitionElements style API was two fold :

- I wanted to avoid a tight coupling with app-history though I'll admit this is a flimsy argument. Especially if we explain the kind of navigations that a page is allowed to control based on what you can observe via app-history.

- Currently app-history doesn't provide an event for back/forward navigations. See the the details [here](https://github.com/WICG/app-history#restrictions-on-firing-canceling-and-responding) : "User-initiated cross-document navigations via browser UI, such as the URL bar, back/forward button" won't fire the navigate event at all. It's worth discussing the thinking behind this with domenic. I can understand why we wouldn't want to make this navigation cancelable. But I don't see why we couldn't provide a non-cancelable event to do other work (like setting up a transition).

The idea of the event dispatching with the final URL is also something I'm currently unsure about. In terms of whether we can keep the old page alive and dispatch an event until after the redirects have been resolved.

**Comment by khushalsagar** [comment] 2022-08-16 22:55
Dupe of the other issue dealing with MPA API shape.

**Closed by khushalsagar** 2022-08-16 22:55 UTC
Labels: api-shape
