### ISSUE TITLE
Should createDocumentTransition be returning a promise that can be awaited?

### ISSUE THREAD

**Issue by vmpstr** [WICG/shared-element-transitions#130] opened 2022-02-24 18:31 UTC
Mostly not sure how to "wait for the callback to happen" and how do we "abandon" transitions, should createDocumentTransition return a promise that allows the developer to know what's happening.

**Comment by khushalsagar** [comment] 2022-03-01 16:05
@vmpstr and I chatted about this and the fact that a single callback with APIs on transition makes it awkward to reason about the lifetime of transition objects. The current API is

```js
document.createDocumentTransition(async (transition) => {
  // add elements to capture.
  transition.setElement(document.documentElement, "root");
  // trigger prepare phase.
  await transition.captureAndHold();
  // update to new DOM.
  await coolFramework.changeTheDOMToPageB();
  // add elements on the new DOM.
  transition.setElement(document.querySelector(".new-message"), "new-message");
  // trigger transition animations. should this return a promise for when the animations finish?
  transition.start();
});
```

The idea behind the async callback here was that we could assume that the transition must be started before the callback returns? It makes it awkward if the author uses a pattern like :

```js
document.createDocumentTransition(async (transition) => {
  transition.setElement(document.documentElement, "root");
  transition.captureAndHold().then( async () => {
    await coolFramework.changeTheDOMToPageB();
    transition.setElement(document.querySelector(".new-message"), "new-message");
    transition.start();
  });
});
```

In this case the callback passed to createDocumentTransition would return but starting the transition happens after that.

In an old issue we had talked about having multiple callbacks where trigger the prepare/start phase happens implicitly when the callback returns. Something like :

```js
document.createDocumentTransition(
  // Dispatched to set up for prepare phase. capture happens when the callback returns.
  async (transition) => {
    transition.setElement(document.documentElement, "root");
  },
  // Dispatched when capture finishes and DOM can change to the new state. Animations start when the callback returns.
  async (transition) => {
    await coolFramework.changeTheDOMToPageB();
    transition.setElement(document.querySelector(".new-message"), "new-message");
  }
);
```

We could probably have a dictionary of callbacks too. There have been requests for an animation phase that happens with snapshots from the old DOM while we're waiting for the new DOM to load. We can introduce a separate callback for that later. So something like :

```js
document.createDocumentTransition({
  prepareCallback : async (transition) => {
    transition.setElement(document.documentElement, "root");
  },
  startCallback : async (transition) => {
    await coolFramework.changeTheDOMToPageB();
    transition.setElement(document.querySelector(".new-message"), "new-message");
  }
});
```

@jakearchibald, how does this sound?

**Comment by flackr** [comment] 2022-03-03 16:45
I've seen several other web apis start with callbacks and move to promises simply for the fact that they are easier to work with, without ending up with multiple levels of nesting. As I understand the problem, there are a few phases of the documentTransition that can be hooked to provide additional behavior. I suggest following a model similar to the [Animation object](https://www.w3.org/TR/web-animations-1/#animation), e.g. this could be something like the following:

```
interface Document {
  Promise<DocumentTransition> createDocumentTransition();
}
interface DocumentTransition {
  readonly attribute Promise<undefined> captured;
  readonly attribute Promise<undefined> ready; // I.e. equivalent to started above.
}
```

With the above interface, captureAndHold would be implicitly triggered by the UA after resolving the createDocumentTransition promise and starting the transition would be implicitly triggered after the captured promise was resolved. This allows the developer to optionally hook those stages if they need to, or ignore them if they don't need to.

With that, I think your example would become something like this:
```js
async function startTransition() {
  let transition = await document.createDocumentTransition();
  transition.setElement(document.documentElement, "root");
  await transition.captured;
  await coolFramework.changeTheDOMToPageB();
  transition.setElement(document.querySelector(".new-message"), "new-message");
  await transition.ready;
}
```

The only tricky part is that if a developer makes a mistake and awaits the promises in the incorrect order they won't get the behavior they expected, however the order should be well specified (just as it is web WebAnimations objects) and they could always use Promise.then to effectively set up listeners for each of the promise resolutions.

**Comment by flackr** [comment] 2022-03-04 16:04
Here's an updated proposal.
```js
async function startTransition() {
  let transition = document.createDocumentTransition();
  transition.setElement(document.documentElement, "root");
  // Calling start immediately captures, then waits for your promise to resolve, then runs the transition.
  let started = transition.start(async () => {
    await coolFramework.changeTheDOMToPageB();
    transition.setElement(document.querySelector(".new-message"), "new-message");
  });
  return started;
}
```

**Comment by khushalsagar** [comment] 2022-03-04 16:09
+1 to flack's proposal.

**Comment by jakearchibald** [comment] 2022-03-09 13:17
The reason I added a callback to `createDocumentTransition` is more about doing the 'best' thing when it comes to errors.

Taking @flackr's first proposal:

```js
async function startTransition() {
  let transition = await document.createDocumentTransition();
  transition.setElement(document.documentElement, "root");
  await transition.captured;
  await coolFramework.changeTheDOMToPageB();
  transition.setElement(document.querySelector(".new-message"), "new-message");
  await transition.ready;
}
```

If `changeTheDOMToPageB` throws/rejects, we don't find out about it, and presumably we end up stuck in the 'captured' state until some timeout. The updated proposal doesn't have that issue, unless we expect there to be async things between creating the transition and starting the transition. Although it seems weird to call `start` before modifying the DOM, since the transition isn't ready yet. I'm also not sure where web-animation-driven transitions would go.

We have these steps:

1. Identify StateA elements that are involved in the transition.
2. Capture and hold StateA.
3. DOM is modified to StateB.
4. Identify StateB elements that are involved in the transition.
5. Create transition elements and custom CSS.
6. Unhold StateA and allow animations to play.
7. Remove transition elements and reveal real StateB.

My assumptions are:

- We hope developers perform required fetches before 1.
- The developer is involved in steps 2 & 4 via CSS and many calls to `setElement`.
  - Can this be done over many microtasks/tasks?
  - What happens if something throws at this point? I guess it's fine and we GC any objects related to the transition once they're out of reference.
- We want to minimise the time between 2 and 3, although forcing it to be synchronous may prevent usage with some existing frameworks. Developers will try and put network stuff in here, so we probably need an intervention there like an aggressive timeout.
- Steps 5 and 6 probably happen together as a single operation (we've been calling this `start`).
- I guess web-animation-api-animations should be created after step 6?
- Something delays step 7. So far we've said "once no pseudo element has an active animation", although should probably define that in a way that allows developers to schedule an additional animation once one completes (eg transition left, then down).

**Comment by jakearchibald** [comment] 2022-03-09 14:43
I'm going to mock up how this will work in React hooks, as this might help us with the API design.

**Comment by flackr** [comment] 2022-03-09 18:39
> ```js
>     // Step 5 and 6 happens when this callback resolves. If an animation
>     // needs to be done using web animations, it can be done in a raf
>     // callback.
>     requestAnimationFrame(() => {
>       document.documentElement.animate(keyframes, {
>         ...animationOptions,
>         pseudoElement: "::page-transition-container(header)",
>       });
>     });
> ```

I would think that resolution of the promise returned from start should occur at the right time to start related web animations, e.g.

```js
  await transition.start(...);
  document.documentElement.animate(keyframes, {
        ...animationOptions,
        pseudoElement: "::page-transition-container(header)",
      });
```

> 
> * If initDOMForTransition() throws we'll be in a bad state, because we expect createDocumentTransition() to be followed up by start() call. But we can fix this so that createDocumentTransition() can be call repeatedly before a start() call happens. Would we want to reset all state (set via setElement) with each new createDocumentTransition() call?

The result of calling `createDocumentTransition()` only needs to construct and return a holder class to set up state on. I don't think it needs to have any actual side effects or costs associated with it moreso than the map of elements it contains. In this way, it wouldn't matter if you repeatedly call it since nothing actually happens until you use one of those instances.

> * The above wouldn't address the issue of driving an animation from script (instead of CSS animations or WA-API) but we already talked about adding another API for that use-case later.

I'd be happy to brainstorm ideas for this, for example, the call to `start` could resolve with the elements involved in the animation which you could then go on to animate by script.

**Comment by jakearchibald** [comment] 2022-03-09 18:44
Gotcha. The new proposed API seems ok, although it seems a bit weird that the callback passed to `start()` is used to delay the start. Maybe it's just a naming issue.

**Comment by jakearchibald** [comment] 2022-03-09 18:47
Here's how it would look as a React hook. It's a little complicated as React performs the DOM update, and just gives you 'hooks' into when things are updated:

```js
function usePageTransition() {
  const startResolver = useRef();

  useEffect(() => {
    const resolver = startResolver.current;
    if (resolver === undefined) return;
    // Step 3 - the DOM has changed
    // Step 4 would happen here, but let's say it isn't needed, & just CSS is used
    
    startResolver.current = undefined;
    // Allow steps 5 onwards to happen.
    resolver();
  });

  return () => {
    return Promise((resolve) => {
      const transition = document.createDocumentTransition()
      // Step 1 would happen here, but let's say it isn't needed, & just CSS is used
      transition.start(async () => {
        // Now in step 2
        resolve();
        await new Promise((resolve) => {
          startResolver.current = resolve;
        });
      });
    });
  };
}
```

Usage:

```js
export default function App() {
  const transitionNextState = useTransition();

  const onClick = async () => {
    await transitionNextState();
    // then change some state
  };

  return …;
};
```

**Comment by khushalsagar** [comment] 2022-03-09 22:23
> I would think that resolution of the promise returned from start should occur at the right time to start related web animations

The promise returned by start resolves when animations on all pseudos have finished and we're going to tear down the pseudo DOM. It's meant to indicate when the transition has completely finished.

The problem is that we don't have an explicit hook for the developer between step 5 (Create transition elements and custom CSS) and step 6 (Unhold StateA and allow animations to play) in Jake's list above. We let the developer update state on |transition| for tagging elements in the new DOM until the end of the async callback. But the pseudo elements are created when this callback resolves, at which point step 5 and step 6 are executed atomically by the browser.

So we don't have an explicit hook in the transitions API where the developer can start accessing pseudo elements created for DOM elements on the new page in script. But raf or any async task (like setTimeout) dispatched at the end of the start callback works.

**Comment by khushalsagar** [comment] 2022-03-10 16:37
I ran into an awkward case when tagging elements in script using this API. The set of elements added using transition.setElement(...) in step 1 persist on the object after start(). IIUC the idea was that if the same element just changes style/layout between 2 DOM transitions then you don't need to tag it again in script.

```js
async function startTransition() {
  let transition = document.createDocumentTransition();
  transition.setElement(document.querySelector(".message"), "message");
  transition.start(() => {
    document.querySelector(".message").transform = 'translate(100px)';
  });
}
```

But if you want to tag a new element on the next page with the same tag then you first need to remove it from the old element using transition.setElement(..) by passing a reference to the old element. This seems silly since the developer would have to retain a reference to the old element. A few options :

- transition.setElement(nullptr, "foo") clears the tag foo and associated element.

- Clear the list of elements on |transition| after capture finishes. So the developer needs to tag elements for the start phase again. I think this would be the common scenario. Developers won't realize that we're retaining references to elements from the old DOM on the |transition| object unless they explicitly clear them.

- Instead of the implicit clear after start above, add an explicit clearElements() API.

**Comment by vmpstr** [comment] 2022-03-10 16:39
See #128 for this discussion

**Comment by khushalsagar** [comment] 2022-03-10 16:43
Sorry, wrong issue. I posted a comment on #128 for discussing this.

**Comment by domchristie** [comment] 2022-05-14 20:19
I created a small library for animating page navigations in server-rendered Turbo Drive (nee Turbolinks) apps, so I'm excited about this direction.

Not sure if this issue is quite the right place, so feel free to (re)move.

I have attempted to implement this new API using the events that Turbo provides, and it's been fun, but I did face a bit of confusion around the lifecycle of a transition; in particular, knowing when the transition snapshot has been taken. This is needed to "pause" the Turbo renderer, just before the DOM is updated to ensure that the correct outgoing snapshot is taken. I solved this by creating a new `snapshot` promise and calling its `resolve` function in the `start` callback. The gist is as follows:

```js
let snapshat
let rendered

// on `turbo:before-render`
let transition = document.createDocumentTransition()
let snapshot = new Promise(resolve => snapshat = resolve)
transition.start(_ => render())
await snapshot

// on `turbo:render`
rendered()

function render () {
  snapshat()
  return new Promise(resolve => rendered = resolve)
}
```

This could be something for the Turbo API to improve on, but I thought I'd share my brief experience.

The demo can be seen here: https://perfect-sparkling-condition.glitch.me/

**Comment by vmpstr** [comment] 2022-05-16 15:44
Hey, thanks for sharing!

Yeah, the premise of this API as Jake mentioned is that it gets to see the state before the DOM transition and after DOM transition, so if we consider something as simple as

```js
transition.start(cb);
```
Then there are the following steps:
1. The `start` call itself is an indication that the current DOM is the previous state, so the browser gets an opportunity to capture the necessary contents into images (this is asynchronous)
2. At some point, the browser is finished capturing things and is ready to invoke `cb` which it does.
3. When `cb` is done executing, the browser assumes that the DOM is now modified to the new state and the transition can begin
4. When the transition finishes, the promise returned by the `start` call is resolved

We found that this API is simple enough that it's "hard to get wrong" in most cases but, of course, it poses some (necessary imho) complexities to frameworks like React or Turbo Drive.

**Comment by khushalsagar** [comment] 2022-08-16 22:44
Final SPA API is in the spec.

**Closed by khushalsagar** 2022-08-16 22:44 UTC
