### ISSUE TITLE
General API shape

### ISSUE THREAD

**Issue by jakearchibald** [WICG/shared-element-transitions#24] opened 2021-04-26 15:40 UTC
```js
document.documentTransition.prepare({
  rootTransition: "reveal-left",
  duration: 300,
  sharedElements: [e1, e2, e3],
}).then(() => {
  changeBodyBackground();
  document.documentTransition.start({ sharedElements: [newE1, newE2, newE3] })
    .then(() => console.log("transition finished"));
});
```

I wonder if this pattern causes issues in cases where `start()` isn't called? Which would happen if `changeBodyBackground` throws.

I assume the intent is:

1. **Prepare browser for transition** - where the browser creates all the required textures for the current state.
2. **Set up the new state** - where the developer modifies the page to represent the new page, and declares which elements are equivalent in a shared element transition.
3. **Perform the transition** - where the browser animates the textures.
4. **Complete** - the transition is complete.

Given this, I wonder if an API a bit like Web Locks would fit:

```js
await document.documentTransition({
  rootTransition: "reveal-left",
  duration: 300,
  sharedElements: [e1, e2, e3],
}, async () => {
  // Step 1 complete
  await changeBodyBackground();
  // Step 2 complete
  // When the promise from this function resolves, that's step 3 complete
  return { sharedElements: [newE1, newE2, newE3] };
});
// Step 4 complete
```

Since it's a callback, the API could detect when things throw etc etc.

**Comment by vmpstr** [comment] 2021-04-26 15:51
TBH, I'm not sure which one is ergonomically better. For what it's worth, the difference between lock-like APIs is that if changeBodyBackground() throws and animation never starts, that's not a bad state. It's just a state in which the animation failed to run. We can still prepare a new animation, or just do nothing. For locks, as I understand them, it's important to know if something went wrong in script land since we need to release the lock.

I do see an argument for API shape consistency though for sure

/cc @chrishtr @ianvollick

**Comment by jakearchibald** [comment] 2021-04-26 16:02
> if changeBodyBackground() throws and animation never starts, that's not a bad state. It's just a state in which the animation failed to run.

Ohh, I thought it worked something like this:

```js
document.documentTransition.prepare(options).then(() => {
  // The display is locked at this point, so if there's layout shifting before `start()` is called
  // it won't be seen
});
```

So if something threw before `start()` was called, the display would be frozen. I guess that isn't the case, and maybe the DOM change has to be synchronous?

The "locks" style of design makes it absolutely clear which "start" is related to which "prepare", and removes the possibility of calling "start" without "prepare".

**Comment by khushalsagar** [comment] 2021-06-30 20:57
For restructuring the API in WebLocks style, just to make sure I understand what you're suggesting : 

```
await document.documentTransition({
  rootTransition: "reveal-left",
  sharedElements: [e1, e2, e3],
  abortSignal: "...",
}, async success => () => {
  // prepare failed.
  if (!success)
    return {};

  // prepare finishes
  await changeBodyBackground();

  // DOM updated to new state. Transition starts when this callback returns.
  return { sharedElements: [newE1, newE2, newE3] };
});
// Promise from above API resolves indicates transition complete.
```

And now that we are going to freeze the display until start is issued, the callback makes it easier to avoid an error in script from keeping the display frozen. The alternate would be for the developer to catch that and explicitly call abort. This sounds like a reasonable argument to me. :)

**Comment by jakearchibald** [comment] 2021-07-01 13:58
What would cause preparation to fail (as in `success` is false)?

**Comment by khushalsagar** [comment] 2021-07-01 16:17
There are a couple of classes of errors where prepare fails : 

- User errors : If you call documentTransition before the previous transition has finished. The current behaviour is to fail the second call if a transition already started. And to fail the first call if prepare hasn't finished yet.

- Internal errors : If memory constraints limit how much we can allocate for snapshots. We don't surface these to script yet, the transition implicitly drops drawing elements which couldn't be captured. But I think it's better to throw an error.

We'd be rejecting the promise returned by the documentTransition in the cases above. But I assumed it's better to invoke the callback instead of silently dropping it.

**Comment by calinoracation** [comment] 2021-07-01 21:25
Really like this and it matches our mental model and desire to use it in our routing layer. Async flows are incredibly common across our workflows and not having paint holding across a boundary would be a huge challenge. With the way it's proposed above, it would expand the number of places and ways we can use this a ton.

It's a very minor detail, but would it might make sense to consider also taking a TaskSignal to pick up priority if that ships soon.

**Comment by jakearchibald** [comment] 2021-07-02 14:28
> * User errors : If you call documentTransition before the previous transition has finished. The current behaviour is to fail the second call if a transition already started.

Would queuing be better?

> And to fail the first call if prepare hasn't finished yet.

In this case the callback shouldn't be called for the first, and the outer promise should reject with a `AbortError` `DOMException`.

> * Internal errors : If memory constraints limit how much we can allocate for snapshots. We don't surface these to script yet, the transition implicitly drops drawing elements which couldn't be captured. But I think it's better to throw an error.

In that case I agree the callback should be called, and `success` should be false. The outer promise should resolve as soon as the inner callback's promise is complete.

**Comment by jakearchibald** [comment] 2021-07-03 11:58
> In general, are you suggesting that all user errors should drop the callback and reject the promise. But internal errors should issue the callback (with success=false) and resolve the promise?

It comes down to whether the callback should happen or not. The callback is what changes the actual content on the page.

If there's a newer navigation that takes priority, running the callback at the same time as running another callback might create weird bugs.

If there's an error in the preparation, it seems like you still want the callback to perform the navigation, but just without a transition.

**Comment by khushalsagar** [comment] 2021-07-07 15:03
Ah I see what you mean. And I'd say it makes sense to continue with the transition if there is any internal error (so dispatch the callback) but abort if there is any user error or even an explicit abort request (from the new abortSignal). Abort would drop the callback and reject the promise.

Also @calinoracation, sorry I missed your comment about TaskSignal earlier. Do you mind explaining the use-case here?

**Comment by calinoracation** [comment] 2021-07-07 15:42
I was mostly curious if the postTask prioritization work made sense here, whether taking an AbortSignal + priority would be useful. It seems that might not be necessary here as we wouldn't be able to have 2 of these operations successfully executing at once if I'm understanding correctly. 

The only real case I could think of is how important is this transition if resources are limited, but I'm not sure that would be really useful and maybe adds more confusion than necessary right now.

**Comment by khushalsagar** [comment] 2022-08-16 22:24
Duplicate of issue #174 now.

**Closed by khushalsagar** 2022-08-16 22:24 UTC
Labels: api-shape
