### ISSUE TITLE
Flash of modified DOM before transition completes

### ISSUE THREAD

**Issue by calinoracation** [WICG/shared-element-transitions#36] opened 2021-06-23 17:01 UTC
I'm trying to implement cover-left / cover-right root transitions and hook them into our History implementation. It sort of works, but I see a flash of the 'next' transition content displayed before start() completes, which is a bit different than what I expected.

I'm applying `contain: paint layout` on the route that I want to be transitioned, but not sure if I need to do some manual work to hide the new layout then unhide it or if I need to specify the route as a shared element. If I specify the route container as a shared element, then I don't even see the cover-in as the whole route doesn't really 'move' per-se.

Does this look like a reasonable use-case that should be accomplishable with this API?

```typescript
const sharedElements: Array<HTMLElement> = [];
await document.documentTransition?.prepare({ rootTransition: 'cover-left' });

originalPush.call(history, location);

await scheduler.postTask(async () => {
  await document.documentTransition?.start({ sharedElements });

  // Wait for a small amount of time after TTFMP to allow a bit of time for the UI to settle.
}, { delay: 200, event: 'TTFMP' });
```

![flash before transition](https://user-images.githubusercontent.com/23196205/123138402-d3e92c00-d409-11eb-8fc9-8d2adec5fcab.gif)

**Comment by khushalsagar** [comment] 2021-06-29 21:26
The issue is that start is being called asynchronously after prepare resolves. When you call start, we'll transition from the snapshot in the last prepare call to the current state. But if there were any DOM updates between prepare/start, we don't stop them from being drawn onscreen. So if you switch to the new layout and then call start asynchronously or with a delay, you'll see a few frames with the new content before the transition starts (which will start by displaying the old content so it feels like a flash).

You mentioned the need for a cancel call in #30 to abort the transition too. Sounds like it would help if the browser avoids redraws (paint holding) after a prepare until we see one of : start, cancel or a reasonable timeout. Since the page should continue receiving  events like input, resize (anything else?), it can also decide to cancel in response to these events if needed.

I was a bit unsure about the aspect of routing input to the "new" DOM while the visual state might be completely different. But this is probably not concerning in practice (could already happen if the page takes too long for a rendering update and input events remain buffered for a while). 

@chrishtr @jakearchibald does the above sound reasonable to you?

**Comment by chrishtr** [comment] 2021-06-29 21:35
Sounds reasonable to me.

**Comment by jakearchibald** [comment] 2021-06-30 12:29
I still feel that Web Locks provides a good API shape here https://github.com/WICG/shared-element-transitions/issues/24. Fwiw, Web Locks takes an abort signal.

**Comment by khushalsagar** [comment] 2021-06-30 20:58
Thanks for the AbortSignal pointer. Seems like it's better to have that as an option in the prepare call instead of a new Cancel API.

I added a comment to #24. The suggestion sounds reasonable to me but that can be taken as a follow up.

**Comment by jeremyroman** [comment] 2021-07-06 19:28
Another option is to require start to occur synchronously during the main frame in which the `prepare()` promise resolves; this is what I'd originally suggested because it limits how long these resources have to be maintained for a transition that might never happen, and it prevents any intermediate changes to the rendering. This of course prevents you from waiting for some asynchronous activity to finish between `prepare` and `start`, but it does mitigate not only this issue and potential security concerns with event targeting being inconsistent with the displayed rendering for an extended period of time.

**Comment by calinoracation** [comment] 2021-07-06 22:40
For our particular use-case requiring start to occur synchronously after prepare might significantly limit being able to use this successfully across a variety of situations.

**Primary use case:**
Intercepting history with delayed rendering, where platform and product code are decoupled, and where we have an async rendering system like React suspense that shows a skeleton screen by default. We need to wait some small amount of time for the shared elements to render and our ability to get a reference to each of them until a small amount of time passes. In this case we want to never show a skeleton loading screen if we have a cached API response, but since it's stored in IndexedDb, it will take at least a tick and 2 renders. 

Being able to read from Indexed DB or hook into `navigate` in the [proposed app-history API](https://github.com/WICG/app-history#example-using-navigateinfo) would open up a ton of opportunities.

**Comment by khushalsagar** [comment] 2021-07-16 18:10
A fix for this landed in chromium and is available on the current Chrome Canary (>= 93.0.4577.0). The browser now freezes visual updates between the prepare promise resolving and a call to the start API.

The prepare API also lets you provide an AbortSignal to abort the transition until the start call : 
document.documentTransition.prepare({
    rootTransition: "reveal-left",
    sharedElements: [e1, e2, e3],
    abortSignal : ".."
  }

This is functionally equivalent to the proposal in #24 and backwards compatible with the existing API. We do plan to restructure the API based on the discussion in #24 but wanted to incorporate feedback from other issues as well.

**Comment by calinoracation** [comment] 2021-07-19 18:27
Thanks, we're excited to try it out again!

**Comment by khushalsagar** [comment] 2021-07-22 17:11
Closing the issue now. Please re-open in case the bug isn't resolved.

**Closed by khushalsagar** 2021-07-22 17:11 UTC
