### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by DylanPiercey** [WICG/shared-element-transitions#152] opened 2022-05-12 22:15 UTC
# Preamble
With many types of server rendered experiences streaming is a first class citizen that can dramatically improve the perceived and actual performance of a page. This is especially true for MPA's which will be hitting the server (and potentially streaming) on each navigation.

Many frameworks are also delivering [out of order streaming](https://tech.ebayinc.com/engineering/async-fragments-rediscovering-progressive-html-rendering-with-marko/).

This includes:
* [Marko](https://markojs.com/#streaming)
* [React](https://reactjs.org/docs/react-dom-server.html#rendertopipeablestream)
* [Solid](https://www.solidjs.com/docs/latest/api#rendertostream)
And probably more.

# Issue
Given https://github.com/WICG/shared-element-transitions/issues/110 it sounds like the plan here on the MPA side is to wait for the completion of rendering before performing the transition. If that is the case that could leave developers in a situation where they choose between fast navigation without transitions and slow navigations with transitions.

Ideally there would be a way to support streaming with these shared element transitions.

# Thoughts
One way I could see this working is by having an "opt in" for incomplete documents. Potentially there could be a list of "required" elements on the page before the transition can begin. Any element that wasn't a part of this required list (if visible on the initial screen) could perhaps just fade away.

**Comment by nxtexe** [comment] 2022-05-12 22:45
I think “required” is a bit too strong, maybe “high priority”. We would want the browser to still be able to ditch a shared element transition if it’s simply not possible.

**Comment by jakearchibald** [comment] 2022-05-13 10:15
Pretty sure this is a dupe of https://github.com/WICG/shared-element-transitions/issues/110.

There's no plan to prevent streaming. The current plan is to start the transition on first render, but allow tangentially-related features like https://html.spec.whatwg.org/multipage/semantics.html#attr-link-blocking to delay first render.

**Closed by jakearchibald** 2022-05-13 10:15 UTC
